const today = new Date();
const dateKey = today.toISOString().slice(0, 10);
const records = [];
const content = document.querySelector('#content');
document.querySelector('#today').textContent = today.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
const empty = '<tr><td class="empty" colspan="8">No attendance records found<br><small>There are no attendance records for the selected period.</small></td></tr>';
function layout(rows) { return `<div class="module"><div class="module-heading"><div><p class="eyebrow">WORKFORCE</p><h1>Attendance</h1><p>Track attendance, working hours and daily work records.</p></div><button class="primary" id="export">↓ &nbsp; Export report</button></div><div class="kpis"><article class="card kpi"><span>Present today</span><strong>${rows.filter(r => r.status === 'Present').length}</strong></article><article class="card kpi"><span>Absent</span><strong>${rows.filter(r => r.status === 'Absent').length}</strong></article><article class="card kpi"><span>Half-day</span><strong>${rows.filter(r => r.status === 'Half-day').length}</strong></article><article class="card kpi"><span>On leave</span><strong>${rows.filter(r => r.status === 'Leave').length}</strong></article></div><section class="card"><div class="controls"><button class="secondary" id="previous">← Previous day</button><button class="secondary" id="next">Next day →</button><input type="date" id="date" value="${dateKey}" aria-label="Attendance date"><div class="segmented"><button class="active" data-mode="daily">Daily</button><button data-mode="weekly">Weekly</button></div><div class="search">⌕ <input id="search" placeholder="Search employees by name or ID..." aria-label="Search employees"></div><select id="status"><option value="All">All statuses</option><option>Present</option><option>Absent</option><option>Half-day</option><option>Leave</option></select></div><div class="summary"><span><b>${rows.length}</b> records</span><span>Only authorized HR records are shown</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Employee ID</th><th>Department</th><th>Check in</th><th>Check out</th><th>Working hours</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.length ? rows.map(r => `<tr><td><div class="person"><span class="avatar">${r.initials}</span><span><strong>${r.name}</strong><small>${r.designation}</small></span></div></td><td>${r.id}</td><td>${r.department}</td><td>${r.checkin || '--'}</td><td class="${!r.checkout ? 'active' : ''}">${r.checkout || (r.checkin ? 'Active' : '--')}</td><td>${r.hours || '--'}</td><td><span class="pill ${r.status === 'Present' ? 'success' : r.status === 'Absent' ? 'danger' : r.status === 'Half-day' ? 'warning' : 'info'}">● ${r.status}</span></td><td><button class="table-action" data-details="${r.id}">View details</button></td></tr>`).join('') : empty}</tbody></table></div><div class="footer"><span>Showing ${rows.length} records</span><span class="pagination"><button disabled>Previous</button><button class="active">1</button><button disabled>Next</button></span></div></section></div>`; }
function render(filtered = records) { content.innerHTML = layout(filtered); document.querySelector('#search').oninput = filter; document.querySelector('#status').onchange = filter; document.querySelector('#date').onchange = filter; document.querySelectorAll('[data-mode]').forEach(b => b.onclick = () => { document.querySelectorAll('[data-mode]').forEach(x => x.classList.toggle('active', x === b)); filter(); }); document.querySelector('#export').onclick = () => alert('Attendance report export started.'); document.querySelector('#previous').onclick = () => alert('Previous day selected.'); document.querySelector('#next').onclick = () => alert('Next day selected.'); document.querySelectorAll('[data-details]').forEach(b => b.onclick = () => alert('Attendance details are available when records exist.')); }
function filter() { const q = document.querySelector('#search').value.toLowerCase(); const s = document.querySelector('#status').value; render(records.filter(r => `${r.name} ${r.id}`.toLowerCase().includes(q) && (s === 'All' || r.status === s))); }
render();