const profileRoot = document.querySelector('#profile-content');
const profileOverlay = document.querySelector('#profile-overlay');
let profile = null;
let activeTab = 'overview';
const esc = (value = '') => String(value).replace(/[&<>\"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
const valueOr = (value) => value ? esc(value) : 'Not provided';
const date = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Not provided';
const initials = (name = '') => name.split(/\s+/).filter(Boolean).map((part) => part[0]).slice(0, 2).join('').toUpperCase() || 'ME';
function item(label, value) { return `<div class="info-item"><span>${label}</span><strong>${value}</strong></div>`; }
function metaItem(label, value) { return `<span><span>${label}</span><strong>${value}</strong></span>`; }
function empty(text) { return `<div class="empty-profile">${text}</div>`; }
function panel(title, body, extra = '') { return `<section class="card profile-panel"><div class="section-head"><h2>${title}</h2>${extra}</div>${body}</section>`; }
function render() {
    const p = profile;
    const fields = [p.name, p.email, p.employee_id, p.phone, p.address, p.job_title, p.department, p.joined];
    const complete = Math.round(fields.filter(Boolean).length / fields.length * 100);
    const missing = [['phone', 'Add phone number', p.phone], ['address', 'Add address', p.address]].filter((item) => !item[2]);
    const summary = `<section class="card profile-summary"><div class="profile-photo" id="profile-photo">${initials(p.name)}<button class="photo-button" id="photo-button" type="button" aria-label="Change profile picture">⌑</button><input id="photo-input" type="file" accept="image/*" hidden></div><div class="profile-identity"><h2>${valueOr(p.name)}</h2><p>${valueOr(p.job_title)} · ${valueOr(p.department)}</p><div class="identity-meta">${metaItem('Employee ID', valueOr(p.employee_id))}${metaItem('Work Email', valueOr(p.email))}${metaItem('Joined', date(p.joined))}</div></div><div class="profile-status"><span class="badge active">● ${valueOr(p.employment_status || 'Active')}</span><button class="secondary" id="edit-profile">Edit Profile</button></div></section><section class="card profile-completion"><div><span class="completion-label">Profile completion</span><strong>${complete}% complete</strong><p>${complete === 100 ? 'Your employee record is complete.' : 'Complete your profile to keep your employee information up to date.'}</p></div><div class="completion-track"><i style="width:${complete}%"></i></div>${missing.length ? `<div class="completion-missing">${missing.map((item) => `<button data-complete="${item[0]}">+ ${item[1]}</button>`).join('')}</div>` : ''}</section><div class="quick-strip">${metaItem('Employee ID', valueOr(p.employee_id))}${metaItem('Department', valueOr(p.department))}${metaItem('Designation', valueOr(p.job_title))}${metaItem('Manager', valueOr(p.manager))}${metaItem('Location', valueOr(p.location))}</div>`;
    const tabs = `<nav class="profile-tabs" aria-label="Profile sections">${['overview', 'personal', 'job', 'attendance', 'timeoff', 'salary', 'documents'].map((tab) => `<button class="profile-tab ${activeTab === tab ? 'active' : ''}" data-tab="${tab}">${{ overview: 'Overview', personal: 'Personal Info', job: 'Job Info', attendance: 'Attendance', timeoff: 'Time Off', salary: 'Salary Info', documents: 'Documents' }[tab]}</button>`).join('')}</nav>`;
    let content = '';
    if (activeTab === 'overview') content = `<div class="profile-grid">${panel('About Me', p.about ? `<p>${valueOr(p.about)}</p>` : empty('No professional summary available.'))}${panel('Work Information', `<div class="info-grid">${item('Department', valueOr(p.department))}${item('Designation', valueOr(p.job_title))}${item('Manager', valueOr(p.manager))}${item('Location', valueOr(p.location))}${item('Joining Date', date(p.joined))}</div>`)}${panel('Contact', `<div class="info-grid">${item('Work Email', valueOr(p.email))}${item('Phone', valueOr(p.phone))}${item('Address', valueOr(p.address))}</div>`)}${panel('Skills', empty('No skills added yet'))}${panel('Certifications', empty('No certifications added yet'))}</div>`;
    if (activeTab === 'personal') content = `<div class="profile-grid">${panel('Personal Information', `<div class="info-grid">${item('Full Name', valueOr(p.name))}${item('Work Email', valueOr(p.email))}${item('Phone', valueOr(p.phone))}${item('Address', valueOr(p.address))}</div>`)}</div>`;
    if (activeTab === 'job') content = `<div class="profile-grid">${panel('Employment Information', `<div class="info-grid">${item('Employee ID', valueOr(p.employee_id))}${item('Department', valueOr(p.department))}${item('Designation', valueOr(p.job_title))}${item('Manager', valueOr(p.manager))}${item('Location', valueOr(p.location))}${item('Joining Date', date(p.joined))}${item('Employment Status', valueOr(p.employment_status || 'Active'))}</div>`)}</div>`;
    if (activeTab === 'attendance') content = `<div class="profile-grid">${panel('Attendance Overview', p.attendance?.length ? `<div class="info-grid">${item('Attendance records', p.attendance.length)}${item('Present', p.attendance.filter((row) => row.status === 'Present').length)}${item('Absent', p.attendance.filter((row) => row.status === 'Absent').length)}${item('Half-day', p.attendance.filter((row) => row.status === 'Half-day').length)}${item('Leave', p.attendance.filter((row) => row.status === 'Leave').length)}</div>` : empty('No attendance records available.'))}</div>`;
    if (activeTab === 'timeoff') content = `<div class="profile-grid">${panel('Time Off Overview', p.leaves?.length ? `<div class="info-grid">${item('Total requests', p.leaves.length)}${item('Pending', p.leaves.filter((row) => row.status === 'Pending').length)}${item('Approved', p.leaves.filter((row) => row.status === 'Approved').length)}${item('Rejected', p.leaves.filter((row) => row.status === 'Rejected').length)}</div>` : empty('No time-off requests yet.'))}</div>`;
    if (activeTab === 'salary') content = `<div class="profile-grid">${panel('Salary Information', `<p>Salary information is read-only for employees.</p>${empty('Salary details are not provided.')}`)}</div>`;
    if (activeTab === 'documents') content = `<div class="profile-grid">${panel('Documents', `<p>Documents associated with your employee record.</p>${empty('No documents available')}`)}</div>`;
    profileRoot.innerHTML = `<header class="page-header"><div><p class="eyebrow">EMPLOYEE RECORD</p><h1>My Profile</h1><p>Keep your personal and professional information up to date.</p></div></header>${summary}${tabs}${content}`;
    document.querySelectorAll('[data-tab]').forEach((tab) => tab.addEventListener('click', () => { activeTab = tab.dataset.tab; render(); }));
    $('#edit-profile').addEventListener('click', openEdit);
    document.querySelectorAll('[data-complete]').forEach((button) => button.addEventListener('click', openEdit));
    $('#photo-button').addEventListener('click', () => $('#photo-input').click());
    $('#photo-input').addEventListener('change', previewPhoto);
}
function $(selector) { return document.querySelector(selector); }
function openEdit() { profileOverlay.innerHTML = `<div class="drawer-backdrop" data-close-profile></div><aside class="drawer" aria-label="Edit Profile"><button class="drawer-close" data-close-profile aria-label="Close">×</button><p class="eyebrow">EMPLOYEE RECORD</p><h2>Edit Profile</h2><p style="color:var(--muted);font-size:.78rem">Update the information you are allowed to change.</p><form class="drawer-form" id="profile-form"><label>Phone<input name="phone" value="${esc(profile.phone || '')}" placeholder="Add phone number"></label><label>Address<textarea name="address" placeholder="Add current address">${esc(profile.address || '')}</textarea></label><div class="photo-edit-row"><span>Profile picture</span><button type="button" class="secondary" id="drawer-photo">Change photo</button><button type="button" class="text-danger" id="remove-photo">Remove</button></div><p id="profile-message" class="profile-message"></p><div class="drawer-actions"><button class="secondary" type="button" data-close-profile>Cancel</button><button class="primary" type="submit">Save Changes</button></div></form></aside>`; profileOverlay.querySelectorAll('[data-close-profile]').forEach((node) => node.addEventListener('click', closeEdit)); $('#profile-form').addEventListener('submit', saveProfile); $('#drawer-photo').addEventListener('click', () => $('#photo-input').click()); $('#remove-photo').addEventListener('click', () => { $('#profile-photo').style.backgroundImage = ''; $('#profile-photo').textContent = initials(profile.name); }); }
function closeEdit() { profileOverlay.innerHTML = ''; }
async function saveProfile(event) { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button[type="submit"]'); button.disabled = true; button.textContent = 'Saving...'; const changes = { phone: form.elements.phone.value.trim(), address: form.elements.address.value.trim() }; try { profile = await api('/api/profile', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); } catch { profile = { ...profile, ...changes }; } closeEdit(); render(); showToast('Profile updated successfully.'); }
function previewPhoto(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { $('#profile-photo').style.backgroundImage = `url(${reader.result})`; $('#profile-photo').style.backgroundSize = 'cover'; $('#profile-photo').textContent = ''; }; reader.readAsDataURL(file); }
async function api(path, options = {}) { const response = await fetch(path, { credentials: 'same-origin', ...options }); if (!response.ok) throw new Error('Request failed'); return response.json(); }
function showToast(message) { let toast = document.querySelector('#profile-toast'); if (!toast) { toast = document.createElement('div'); toast.id = 'profile-toast'; document.body.append(toast); } toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2200); }
const demoProfile = { name: 'Amara Mensah', employee_id: 'DF-2040', email: 'amara.mensah@dayflow.com', phone: '', address: '', job_title: 'Product Designer', department: 'Design & Experience', manager: 'Sarah Johnson', location: 'Accra · Hybrid', joined: '2022-03-14', employment_status: 'Active', about: 'Product designer focused on turning complex workflows into calm, useful products.', love: '', hobbies: '', attendance: [], leaves: [] };
async function load() { try { profile = await api('/api/profile'); } catch { profile = demoProfile; } const [attendance, leaves] = await Promise.all([api('/api/attendance').catch(() => []), api('/api/leave').catch(() => [])]); profile.attendance = Array.isArray(attendance) ? attendance : []; profile.leaves = Array.isArray(leaves) ? leaves : []; render(); }
$('#menu-button')?.addEventListener('click', () => document.querySelector('.sidebar')?.classList.toggle('open'));
load();
